sudo: false

language: python

python:
   - "3.6"

before_install:
    - cat .travis.yml
    - pip install --upgrade pip
    - pip --version

install:
    - pip install coverage
    - pip install mypy
    - pip install pylint
    - pip install numpy
    - pip list

before_script:
    - date
    - uname -a
    - printenv | sort
    - cmake      --version
    - coverage  --version
    - git       --version
    - make      --version
    - mypy      --version
    - pylint    --version
    - python3.6 --version
    - ls -al
    - cat makefile

script:
    - make travis
